name: pcl_viewer
description: HP PCL Viewer(translater) made by BOBA.inc
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dotted_border: ^2.0.0+3
  desktop_drop: ^0.4.1
  open_file: ^3.2.1
  path_provider: ^2.0.14
  file_picker: ^4.6.1
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.10
  window_manager: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - bin/